spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    host: localhost
    port: 3306
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/accountBook?serverTimezone=UTC&characterEncoding=UTF-8
    schema: classpath:schema.sql