spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/accountBook?serverTimezone=UTC&characterEncoding=UTF-8
    schema: classpath:schema.sql